### ISSUE TITLE
Config Crash

### ISSUE THREAD

**Issue by opencma** [rolandoislas/drc-sim-client#10]
The crash appears to happen after a config option is changed.
```
java.lang.ClassCastException: 
  at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:235)
  at com.badlogic.gdx.backends.android.AndroidPreferences.getString(AndroidPreferences.java:106)
  at com.rolandoislas.drcsimclient.config.ConfigControllerConfig.get(ConfigControllerConfig.java:51)
  at com.rolandoislas.drcsimclient.stage.StageConfigController.addItems(StageConfigController.java:64)
  at com.rolandoislas.drcsimclient.stage.StageConfigController.<init>(StageConfigController.java:56)
  at java.lang.Class.newInstance(Native Method:0)
  at com.rolandoislas.drcsimclient.stage.StageList$2.changed(StageList.java:110)
  at com.rolandoislas.drcsimclient.stage.StageList.listItemSelected(StageList.java:97)
  at com.rolandoislas.drcsimclient.stage.StageList.access$000(StageList.java:21)
  at com.rolandoislas.drcsimclient.stage.StageList$1.changed(StageList.java:44)
  at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
  at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
  at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
  at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:218)
  at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:52)
  at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:46)
  at com.badlogic.gdx.scenes.scene2d.ui.List.touchDown(List.java:86)
  at com.badlogic.gdx.scenes.scene2d.ui.List$1.touchDown(List.java:70)
  at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:56)
  at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
  at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
  at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:282)
  at com.badlogic.gdx.backends.android.AndroidInput.processEvents(AndroidInput.java:375)
  at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:457)
  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
```

**Comment by Grntrenchman** [comment]
Confirmed issue fixed in 2.0 beta. App no longer crashes on setting controller options.
