### ISSUE TITLE
Exception in thread "LWJGL Application" when 2nd display plugged in

### ISSUE THREAD

**Issue by Carbuino** [rolandoislas/drc-sim-client#18]
So this happened when I had my TV plugged in to my PC:

wg93589@DS-Ubuntu:~$ java -jar '/home/wg93589/Desktop/drc-sim-client-2.0-beta-3.jar'
Sun Jun 11 18:29:22 MDT 2017 WARNING:drcsim Failed to create log file.
Sun Jun 11 18:29:22 MDT 2017 INFO:drcsim Starting DRC Sim Client version 2.0
Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:558)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:122)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 2 more
AL lib: (EE) alc_cleanup: 1 device not closed

It fixed its self after I unplugged it.

OS: Ubuntu 16.04
Java Version: openjdk version "1.8.0_131"

**Comment by opencma** [comment]
Is this a clean Ubuntu 16.04 install?

Possible resolution: http://badlogicgames.com/forum/viewtopic.php?f=11&t=18801

In simmary: `sudo apt install x11-xserver-utils`.
